package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/danhorst/second-opinion/skills"
)

const skillUsage = `usage: second-opinion skill install [--harness claude|codex|all] [--stdout]

  --harness H  install for one harness (default: all)
  --stdout     print the canonical skill instead of installing

Antigravity consumes the skill as a plugin: the installer writes one under
~/.second-opinion/antigravity-plugin and runs "agy plugin install <dir>"
when agy is on PATH.
`

const generatedStamp = "<!-- generated by second-opinion skill install; edits will be overwritten -->"

// pluginJSON is the minimal manifest agy's plugin validator accepts
// (verified against agy 1.1.0: plugin.json + skills/<name>/SKILL.md).
const pluginJSON = `{"name":"second-opinion","version":"0.1.0","description":"Adversarial second opinion via the second-opinion CLI"}
`

// skillDeps are the installer's injected edges, so tests run against a temp
// home and a recording fake instead of the real agy.
type skillDeps struct {
	home       string
	lookPath   func(name string) (string, error)
	runInstall func(pluginDir string) (output string, err error)
}

// renderClaude is the canonical skill with the generated stamp inserted
// after the frontmatter — the frontmatter itself is Claude's native format.
func renderClaude() string {
	front, body := splitFrontmatter(skills.SecondOpinion)
	return front + generatedStamp + "\n" + body
}

// renderCodex strips the frontmatter — codex custom prompts are plain
// markdown and the filename is the command name.
func renderCodex() string {
	_, body := splitFrontmatter(skills.SecondOpinion)
	return generatedStamp + "\n\n" + strings.TrimLeft(body, "\n")
}

// splitFrontmatter separates a leading YAML frontmatter block (--- ... ---)
// from the body. Without one, front is empty.
func splitFrontmatter(doc string) (front, body string) {
	const fence = "---\n"
	if !strings.HasPrefix(doc, fence) {
		return "", doc
	}
	end := strings.Index(doc[len(fence):], fence)
	if end < 0 {
		return "", doc
	}
	cut := len(fence) + end + len(fence)
	return doc[:cut], doc[cut:]
}

func runSkill(args []string, deps skillDeps, stdout, stderr io.Writer) int {
	if len(args) == 0 || args[0] != "install" {
		fmt.Fprint(stderr, skillUsage)
		return 2
	}
	harness := "all"
	toStdout := false
	for i := 1; i < len(args); i++ {
		switch arg := args[i]; arg {
		case "--stdout":
			toStdout = true
		case "--harness":
			i++
			if i >= len(args) {
				fmt.Fprintf(stderr, "second-opinion: --harness requires a value\n%s", skillUsage)
				return 2
			}
			harness = args[i]
		default:
			fmt.Fprintf(stderr, "second-opinion: unknown flag: %s\n%s", arg, skillUsage)
			return 2
		}
	}
	if toStdout {
		fmt.Fprint(stdout, skills.SecondOpinion)
		return 0
	}

	targets := map[string]struct {
		path    string
		content string
	}{
		"claude": {filepath.Join(deps.home, ".claude", "skills", "second-opinion", "SKILL.md"), renderClaude()},
		"codex":  {filepath.Join(deps.home, ".codex", "prompts", "second-opinion.md"), renderCodex()},
	}
	names := []string{"claude", "codex"}
	if harness != "all" {
		if _, ok := targets[harness]; !ok {
			fmt.Fprintf(stderr, "second-opinion: unknown harness %q (claude, codex, all)\n", harness)
			return 2
		}
		names = []string{harness}
	}

	for _, name := range names {
		t := targets[name]
		if err := os.MkdirAll(filepath.Dir(t.path), 0o755); err != nil {
			fmt.Fprintf(stderr, "second-opinion: %v\n", err)
			return 1
		}
		if err := os.WriteFile(t.path, []byte(t.content), 0o644); err != nil {
			fmt.Fprintf(stderr, "second-opinion: %v\n", err)
			return 1
		}
		fmt.Fprintf(stdout, "installed %s skill: %s\n", name, t.path)
	}

	// Antigravity consumes the skill as a plugin installed from a stable
	// tool-owned directory (agy imports Claude *plugins*, not bare skills —
	// learned empirically; see the change's design doc).
	if harness == "all" || harness == "claude" {
		pluginDir := filepath.Join(deps.home, ".second-opinion", "antigravity-plugin")
		files := map[string]string{
			filepath.Join(pluginDir, "plugin.json"):                          pluginJSON,
			filepath.Join(pluginDir, "skills", "second-opinion", "SKILL.md"): renderClaude(),
		}
		for path, content := range files {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				fmt.Fprintf(stderr, "second-opinion: %v\n", err)
				return 1
			}
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				fmt.Fprintf(stderr, "second-opinion: %v\n", err)
				return 1
			}
		}
		if _, err := deps.lookPath("agy"); err == nil {
			if out, err := deps.runInstall(pluginDir); err != nil {
				fmt.Fprintf(stderr, "warning: agy plugin install failed: %v\n%s", err, out)
			} else {
				fmt.Fprintf(stdout, "installed antigravity plugin via agy plugin install %s\n", pluginDir)
			}
		} else {
			fmt.Fprintf(stdout, "antigravity: agy not found; run `agy plugin install %s` after installing it\n", pluginDir)
		}
	}
	return 0
}
